<?php


class Plane extends Vehicle
{
    /**
     * @var int
     */
    private $maxAlt;


    public function move(int $kilometers)
    {
        parent::move($kilometers); // TODO: Change the autogenerated stub
        echo 'Vroum-Vroum';
    }

    /**
     * @return int
     */
    public function getMaxAlt(): int
    {
        return $this->maxAlt;
    }

    /**
     * @param int $maxAlt
     */
    public function setMaxAlt(int $maxAlt): void
    {
        $this->maxAlt = $maxAlt;
    }


}